### ISSUE TITLE
I faced an issue when I tried to build this project.

### ISSUE THREAD

**Issue by golddydev** [neon-mmd/websurfx#134]
I cloned this project and run the following commands.
```
git clone https://github.com/neon-mmd/websurfx.git
cd websurfx
git checkout stable
cargo build -r
```
I faced error when I run this command.
`cargo build -r`

**What happened?**

error[E0635]: unknown feature `proc_macro_span_shrink` 

![image](https://github.com/neon-mmd/websurfx/assets/122273317/e84e3aa2-8fc6-42e4-a6fa-be8985155a89)

Can anybody help me with my issue?

**Comment by neon-mmd** [comment]
Yes sure 🙂, we would be glad to help you out, but can you please let us know what version of rust you are using by running the following in your terminal:

rustc --version

And also let us know what toolchain you are using, like you are using nightly or stable to build the program.

Also, If you wish to be on the latest and greatest changes then I would suggest using the rolling branch by running the following commands:

git clone https://github.com/neon-mmd/websurfx.git
cd websurfx
cargo build -r

Thanks ❤️ for filing this bug and highlighting this issue. It really helps improve the project 🙂.

**Comment by golddydev** [comment]
You mean rustc version?
I use rustc 1.72.0, cargo 1.72.0.

**Comment by neon-mmd** [comment]
> You mean rustc version? I use rustc 1.72.0, cargo 1.72.0.

Yes, this was what we were wanting to know :slightly_smiling_face:  , thanks :heart:. It seems that you are using the nightly version of rust, which we don't recommend using, as our project also aims at providing stability. Though, we don't stop users from using nightly version of rust, but we leave it on their own risk. So I would suggest using a stable version of rust. In order to use a stable version of rust, you will need to run the following commands:

```shell
cd websurfx
rustup default stable
```

And then you can build the program as usual using the `cargo build -r` command :slightly_smiling_face: .

**Comment by golddydev** [comment]
Yes, this is fixed by changing the rustc version to stable.
