### ISSUE TITLE
✨ Public instances section in the readme.

### ISSUE THREAD

**Issue by ghost** [neon-mmd/websurfx#213]
**Is your feature request related to a problem? Please describe.**
I cannot find public instances to use, thus adding even empty section of public instances will signal interest for those who can host it.

**Describe the solution you'd like**
Add public instances section in the read me file
**Describe alternatives you've considered**
Having an external website to index websurfx instances
**Additional context**
https://searx.space/

**Comment by neon-mmd** [comment]
> **Is your feature request related to a problem? Please describe.** I cannot find public instances to use, thus adding even empty section of public instances will signal interest for those who can host it.
> 
> **Describe the solution you'd like** Add public instances section in the read me file **Describe alternatives you've considered** Having an external website to index websurfx instances **Additional context** https://searx.space/

Sorry for being late to reply, I just got a little busy. Thanks :heart: for taking the time to requesting this feature. This really helps us improve the project. So we really appreciate it :+1: . This was already in our plan list, but I think right now having a website might not be a good idea since we are still not very big of a project. So I think maybe we can have an instances.md page in our page in our readme where users can get their instances listed with a PR. What do you think ?

**Comment by ghost** [comment]
If you linked to it from the main read me file, I think this will be great.

**Comment by neon-mmd** [comment]
> If you linked to it from the main read me file, I think this will be great.

Ok thanks :heart:. I think it is a great suggestion and I think I will work on the same in the next PR soon. :slightly_smiling_face:

**Comment by alamin655** [comment]
Feature request addressed as of PR #253, #262, and #267. 🚀

We've implemented the requested feature, and it should now be available. If you have any additional feedback or encounter any issues with the new functionality, please feel free to reopen this issue or open a new one. Your input helps us improve! 😊

---
We have a [Discord server](https://discord.gg/SWnda7Mw5u); feel free to join and share your ideas and ask questions about the project. We would be glad to hear from you.
