### ISSUE TITLE
✨ Mirror repo for the current project

### ISSUE THREAD

**Issue by ghost** [neon-mmd/websurfx#217]
**Is your feature request related to a problem? Please describe.**
I think it's pretty important for open-source project to host their code on open source platform.

**Describe the solution you'd like**
host or mirror the code into open-source platform.

**Describe alternatives you've considered**
mirroring the code for example on gitlab or  hosting it from there.

**Additional context**

**Comment by neon-mmd** [comment]
Thanks :heart: for taking the time to open this issue. This is a good suggestion, I appreciate it :+1: and I would love to also have a mirror on an open source platform too. But I think right now having a mirror on another platform would not be very viable because right now this project is relatively very small, so it would not make sense to have it on another platform this early. Also, About hosting on another platform is great, but the issue with GitLab or any other platform is that they are pretty unfamiliar to most people like developers. Which means that if I were to move it over there it would add a huge learning curve which will make contributions a lot less. That's why you will see that a lot of open source projects prefer GitHub for the reason I discussed. Also, I don't mean that I don't want to have mirrors on open source platforms. I would be glad to have my repository mirrored there, but for now, since I discussed this project is relatively small, so I think it won't be very viable. :slightly_smiling_face:

**Comment by neon-mmd** [comment]
Thanks :heart: again for opening this issue, now we have mirrored this project to 2 new git repositories, one to GitLab and the other to Gitea. The mirror repositories for both of which can be found here, and we would suggest taking a look and providing us with some feedback :slightly_smiling_face: :

- `Gitea:` https://mirror.websurfx.pp.ua/
- `GitLab:` https://gitlab.com/chaos-os/websurfx

**Comment by ghost** [comment]
Thank you, I will close as it's solved.
