### ISSUE TITLE
📝 Discussion on changes regarding the `Code of conduct`

### ISSUE THREAD

**Issue by Sweetdevil144** [neon-mmd/websurfx#264]
### Description

I have found that the `code of conduct` file is very unreadable. So I am thinking of updating it to improving its readability, but since neon-mmd pointed out that it is a very sensitive file and a minor change could have wide consequences. On neon-mmd's suggestion, I have opened this issue to discuss whether should I make the changes or not. ?     

### Do you want to work on this issue?

None

**Comment by neon-mmd** [comment]
I think I would suggest updating the `Code of conduct` file, but I would like to suggest a few things to remember when you update the `Code of conduct` these are:

- The `code of conduct` of these projects has been written by borrowing guidelines from the following `code of conducts` which I would strongly suggest having a look:
  - https://github.com/twitter/.github/blob/main/code-of-conduct.md
  - https://www.rust-lang.org/policies/code-of-conduct
  - https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md
  - https://github.com/domgetter/NCoC/blob/master/README.md
- Some guidelines of the `code of conduct` are added by the project in order to ensure a safer environment for anyone involved in the project. These guidelines include:
  -  `Jokes are allowed, but they should not be mean't to insult anyone` : This was adopted to create a safe environment for everyone so that nobody is insulted or bullied in the project.
  - `Bad words or cursing are not allowed`: This was adopted in order to create safe environment by `giving respect to each other` and not making anybody feel bad or angry and cause unnecessary drama like fights, etc. 
  - `Treat everyone equally` : This was adopted to create a safe environment by letting everyone know that they are all adults and mature people, Maturity in the sense that we believe `giving respects to each other` and we don't care of who you are. We just care that you are a human being, then you are welcomed, and as such we treat everyone as our brothers and sisters. 
- Other important guidelines that were adopted from other `code of conducts` . These include:
   - `twitter code of conduct section "What We Strive at"` 
   -  `pledge section from github code of conduct`
   - `Violations and action to be taken from github code of conduct`
   - `Reporting issues section from twitter's code of conduct`
 
So when you update the `code of conduct` file make sure to changes very carefully like it should not change the meaning of something. Also, make sure every detail is complete, don't remove necessary details which could be helpful for anybody reporting anything to the project maintainers. 

So with that in mind, make sure to update the `code of conduct` carefully. Also, I would suggest examining each change a few times before you make it 🙂 .  

@alamin655 @xffxff @arctic-byte What are your thoughts on this ?? Any suggestions ?? 🙂

**Comment by Sweetdevil144** [comment]
I sure will. Thanks for the continuous support and numerous suggestions btw. I'll give a regular update on changes being performed.

**Comment by Sweetdevil144** [comment]
Fix available soon via #261.

**Comment by Sweetdevil144** [comment]
Can we add the label of #hacktoberfest to it?

**Comment by neon-mmd** [comment]
> Can we add the label of #hacktoberfest to it?

I think it won't be a good idea because `Hacktoberfest` label tends to be oriented towards newcomers to a project. So if we add the Hacktoberfest label to this. This will bring a lot of newcomers to the project, that is good, but by seeing the complexity of the work to be done they might not do it.  This will in turn add a bad reputation to the project, which is not good. Moreover, some people might be interested to work on, but they might not have any idea of the project, the codebase, etc. I hope you got my point :slightly_smiling_face: .

Also, I would like to suggest one thing. Can we have this talk somewhere else, like on the discord? Because I think this would be a better place to have a talk on this topic. What do you think ? :slightly_smiling_face: .

**Comment by Sweetdevil144** [comment]
> I hope you got my point 🙂 .

**Yeah sure. 😄**

> Also, I would like to suggest one thing. Can we have this talk somewhere else, like on the discord? Because I think this would be a better place to have a talk on this topic. What do you think ? 🙂 .

**Definately @neon-mmd 😄**
