### ISSUE TITLE
Why is Lua used for writing configurations?

### ISSUE THREAD

**Issue by XFFXFF** [neon-mmd/websurfx#35]
Why are we using Lua for [configuration](https://github.com/neon-mmd/websurfx/blob/master/websurfx/config.lua) instead of other formats like YAML? I don't have any experience with Lua, so I'm curious about the benefits of using it for configuration files.

For example, I would like to introduce configurations similar to the following:

```
aggregator:
  random_delay: true
  engines:
    duckduckgo
    searx
```

I am unsure how to implement this with Lua, and it may be more straightforward with YAML.

**Comment by neon-mmd** [comment]
Thanks for opening a discussion on this topic :smile:. Let me explain why are we using Lua instead of Yaml as a config.

The main idea behind using Lua is that it provides a lot of flexibility and control to the user, let's say for example consider this scenario The user is hosting the server on several devices at once now if we Yaml as a config file the person will have to maintain for separate `config.yml` file each tweaked for that device which is tedious and let's say if we introduce a breaking change then the person will have to edit all four `config.yml` files which is painfully tedious and will give a bad user experience instead having `config.lua` will be more efficient because the person will have to maintain one single file where he can add conditions for different devices which might look something like this:

```lua
if os.operating_system == "windows" then
    do this
elseif os.operating_system == "linux" then
    do this
elseif os.operating_system == "android" then
    do this
else
    do this
```

Now even if a breaking change appears the person will need to only edit one single file and will not have to maintain 4 separate configs. Also, there is another added benefit someone could also write scripts that will allow the user to modify the config under certain circumstances and final benefit is that someone could go as far as to have one config file to handle the case of having one single config file for a different version of the same operating system which would look something like this:

```lua
if os.operating_system == "ubuntu" then
   if os.version == "22.04" then
      do this
   elseif os.version == "16.04" then
      do this
   else
      do this
```

Overall, it will provide the user will a lot more control over their configs.

**Comment by XFFXFF** [comment]
@neon-mmd Thank you for taking the time to explain everything so clearly and patiently. It was very reasonable and easy to understand

**Comment by neon-mmd** [comment]
You are welcome :slightly_smiling_face: .
