### ISSUE TITLE
🐛 Something goes wrong with `stylelint`

### ISSUE THREAD

**Issue by willser** [neon-mmd/websurfx#374]
### Description

Hello team,

You do a great job,this is an amazing repository! 😄 

I am new to this repo and I follow the deveploping.md to install software I need.When I try to make a commit,I noticed it falured cause pre-hook which is .rusty-hook.toml.So I run the  pre-commit command.And I get following error.

```
......

public/static/colorschemes/dracula.css
  4:16  ✖  Expected "#ff5555" to be "#f55"  color-hex-length
 10:18  ✖  Expected "#ffffff" to be "#fff"  color-hex-length

public/static/colorschemes/gruvbox-dark.css
 10:18  ✖  Expected "#ffffff" to be "#fff"  color-hex-length

public/static/colorschemes/monokai.css
 10:18  ✖  Expected "#ffffff" to be "#fff"  color-hex-length

46 problems (46 errors, 0 warnings)

```

I read [deveploping.md](https://github.com/neon-mmd/websurfx/blob/rolling/docs/developing.md?plain=1#L55-L57) again and found I do miss nothing instand of `cargo watch` casuse I don't need it.

So it's that something wrong with `stylelint` or I install wrong version?
```
➜ stylelint --version
15.11.0

```

### Do you want to work on this issue?

None

**Comment by neon-mmd** [comment]
Thanks ❤️ for taking the time to report this issue. We really appreciate it 👍, as it helps improve the project.

Don't worry you have installed the project the right away just that this error is known and we are already planning to work on a fix for it and it would be provided soon. 🙂  So in the meanwhile we would suggest commiting the PR with this command instead:

``` shell
git commit --no-verify
```

**Comment by neon-mmd** [comment]
willser, Now we have fixed this issue and as such we would suggest you to update your fork with new changes (if you don't know how to update your fork then a link to tutorial has been provided down below I would suggest checking it out) and then run the following commands (shown below) in your local working repository in the branch you are working on which should probably be named something like this `TEST/179_more-unit-tests-integration-tests-and-doc-tests`.

```shell
git pull
git merge rolling
```

and then commit your changes by running the following command:

```shell
git commit
```

and after running the above command if you still face any issues let us know by commenting your problem on this issue. otherwise if your problem has been resolved then we would suggest closing this issue :slightly_smiling_face: .  

## Reference 
- [A tutorial on how to update your fork with another project as an example](https://piped.kavin.rocks/watch?v=eze7Y4Rxwtc)

**Comment by willser** [comment]
Thank you!I would update my branch.
