### ISSUE TITLE
💄improve visual fidelity for `simple` theme

### ISSUE THREAD

**Issue by cybrejon** [neon-mmd/websurfx#405]
### Why this is important
websurfx's front-end appears to be quite visually dated. Appearance is a good first impression if your first-time visitors don't know what to expect yet. A well thought-out design helps with user retention this way.

### General (suggested) changes/improvements
- improve proportions to keep components looking cohesive across the site 
- observe proper alignment and spacing to improve focal points
- improve color contrast for better content separation and emphasis
- adjust white-space to compliment a more modern design and allow for more breathing space

### How
Prototyping will be done using Figma and the browser extension called Stylus to inject custom css in the front-end during runtime. This will allow me to mitigate the lack of hot reloads and drastically speed up development.

### Where/What
Modifications will take place in simple.css (`public/static/themes/simple.css`) and will be made compatible with color schemes.

### Do you want to work on this issue?

Yes

**Comment by neon-mmd** [comment]
Thanks ❤️ for taking the time opening this issue. We really appreciate it 👍 as it helps improve the project. Since you have mentioned you want to work on this issue so we are assigning this issue to you. You may start working it right away 🚀 🙂 .

But also, a few things to note before you work on this issue which we feel might be important:
- Every theme in this project has the ability to change colorschemes like for example the simple theme by default uses catpuccin theme but you can change this by going into the UI settings or via the config file (by server admins) and changing it to tokyo-night or something else all togather. This approach has been done in order to provide more customizability to the user.
- Also, the web page are not responsive at present at least some pages like the settings page and the home page. Also we think this issues can be fixed by using a different css layout altogather called `grid` which can both reduce file size which improves page load as well as make page more responsive and we also have an issue opened for this already. So we would suggest not doing it in this issue.

**Comment by cybrejon** [comment]
> - Every theme in this project has the ability to change colorschemes like for example the simple theme by default uses catpuccin theme but you can change this by going into the UI settings or via the config file (by server admins) and changing it to tokyo-night or something else all togather. This approach has been done in order to provide more customizability to the user.
> - Also, the web page are not responsive at present at least some pages like the settings page and the home page. Also we think this issues can be fixed by using a different css layout altogather called grid which can both reduce file size which improves page load as well as make page more responsive and we also have an issue opened for this already. So we would suggest not doing it in this issue.

Awesome, i'll keep these in mind.
