### ISSUE TITLE
⚡️A couple of optimizations for improving performance

### ISSUE THREAD

**Issue by lxrst** [neon-mmd/websurfx#406]
### Description

I only found this project recently, but I've been playing around with it some.

I've found some potential optimizations:
 - The safe search value is passed around as a `u8` which is prone to misuse and perf hits. An enum implementing `Order` would be better.
 - There's very heavy use of libstd `Vec`, which isn't the best option in all situations. I think I was looking at the aggregator.
 - Excessive disk I/O operations
 - Using `reqwest` for HTTP requests is fine, but it's not the best for speed. By using raw `hyper`, you work with connections and requests, which allows you to keep open and use the same connections.

Also, some miscellaneous nit-picking:
 - I don't know anything about `mimalloc` other than what I've read on its crates.io page, but you generally don't need a non-standard allocator outside of embedded systems and other small environments. Is there a reason it's needed?
 - The project structure is a little non-Rusty (e.g. `models/aggregation_models.rs` would be better as `models/aggregation.rs`)

### Do you want to work on this issue?

Yes

### Additional information

This project is very interesting and I'm excited to see where it goes!

**Comment by ashwinvin** [comment]
Switching to use `hyper` instead of `reqwest` would add to code debt. Besides that `reqwest::Client` holds a connection pool internally so, I don't think we could be able to gain better speed.

**Comment by neon-mmd** [comment]
Thanks ❤️ for taking the time to open this issue. We really appreciate it 👍 as it helps improve the project. 🙂 

Since you have requested to work on this issue. We would assign this issue to you right away 🚀 . You may start working on it now 🙂 .

But before you we would like to discuss a few things based on your suggestions and questions:
- We totally agree with you on the `vec` things and would love to see optimizations in this area. We have already have done some in the past by replacing some usage of vectors with `smallvec` to reduce memory usage and improve performance.
- Again, we agree with your suggestions about using `hyper` over `reqwest` but the issue is that hyper's api changes too often which means it breaks everything all the time and can be quite hard to maintain that's why we had avoided using it over reqwest till now. but would still love to hear from you if you have a better way of maintaining it or any ideas on this. 🙂 
- About the inclusion of `mimalloc` we have done this because of three reasons first speed, safety and another side goal for supporting low memory devices in future like for example supporting devices like mobile phones, tablets, etc. Now you may ask `why support low memory devices?` The reason behind this is that many people do have old devices like old phones, tablets, etc laying around there house but they have absolutely no use so what we are planning to do is that by supporting such devices we can give users the ability to repurpose their old devices for self-hosting websurfx and having their own instance for personal use. We hope you got our point 🙂 .
- Also, we think for the project structure part we would suggest having a new issue/PR because this could be better to have it in other issue as it looks pretty unrelated with the changes you suggested. Also having it in a new issue/PR would be better as it make reviewing the PR by anybody easier.
- For other optimizations and suggestions we totally agree with you, it is a yes from our side and we would suggest working on it. 

Also, one final suggest we would like to make since you are new to the project. We would suggest you to also have a look at the `developer guide` which covers everything you need to get started in the project like it covers from project structure to project workflow. So we highly recommend you to go through it.

Here is the link to the developer guide:

https://github.com/neon-mmd/websurfx/blob/rolling/docs/developing.md

**Comment by lxrst** [comment]
> hyper's api changes too often which means it breaks everything all the time and can be quite hard to maintain

`hyper` actually released v1.0 earlier this month! :D
I'm comfortable with `hyper` and would be happy to help maintain it, although my contributions may be sporadic.

 > supporting low memory devices in future like for example supporting devices like mobile phones, tablets, etc.

Yes, I understand and completely agree with this reasoning. I use a collection of Raspberry Pi's and crappy laptops. Rust's default allocator should be fine for such environments. It shouldn't cause any considerable increase in resource usage. Alternate ones are usually used by people trying for very small code (think microcontrollers)

**Comment by neon-mmd** [comment]
> > hyper's api changes too often which means it breaks everything all the time and can be quite hard to maintain
> 
> `hyper` actually released v1.0 earlier this month! :D I'm comfortable with `hyper` and would be happy to help maintain it, although my contributions may be sporadic.

Ok cool :rocket:, but I would like to also suggest having connection pooling with `hyper` like `reqwest` does, otherwise the advantages of using `hyper` over `reqwest` would be very minimal and not very effective. :slightly_smiling_face: 

> > supporting low memory devices in future like for example supporting devices like mobile phones, tablets, etc.
> 
> Yes, I understand and completely agree with this reasoning. I use a collection of Raspberry Pi's and crappy laptops. Rust's default allocator should be fine for such environments. It shouldn't cause any considerable increase in resource usage. Alternate ones are usually used by people trying for very small code (think microcontrollers)

Actually, as discussed there are other two reasons too like speed and security, like `mimalloc` tends to more performant and secure in allocations then other allocators. Also, this is something which aligns with the main goals of the project, that's why we have included. I hope you got my point. :slightly_smiling_face: 

Here is a link to the `mimalloc` project `readme` which specifies the goal of `mimalloc` as an alternative. It states in the advantages like it avoids many memory vulnerabilities associated with heap, and also it states about being fast. Which I would suggest going through :slightly_smiling_face: :

https://github.com/microsoft/mimalloc/blob/master/readme.md

**Comment by neon-mmd** [comment]
lxrst, it has been one week so far, any progress on this issue so far? We would like to know :slightly_smiling_face: .

**Comment by lxrst** [comment]
Sorry, I've been busy with work and haven't had a ton of time to work on open source. There's been some changes in rustls/webpki that I'd like to fully investigate. By the time I actually get around to this, I'll probably need to rewrite my modifications anyway.
I'll have much more time to work on this next week. Thanks for understanding!

**Comment by neon-mmd** [comment]
> Sorry, I've been busy with work and haven't had a ton of time to work on open source. There's been some changes in rustls/webpki that I'd like to fully investigate. By the time I actually get around to this, I'll probably need to rewrite my modifications anyway. I'll have much more time to work on this next week. Thanks for understanding!

Thanks ❤️ for updating us on this issue. We really appreciate it 👍. No need to be sorry, about it, take your time, but we would suggest just keep us updated on the issue 🙂.

Also, if you prefer to update us on another place other than here, then we would recommend joining our discord server and keep us updated over there. 🙂

**Comment by neon-mmd** [comment]
lxrst, it has been one week again, any progress on this issue so far? We would like to know :slightly_smiling_face: .

**Comment by neon-mmd** [comment]
@lxrst it has been two weeks, any progress on this issue so far? We would like to know :slightly_smiling_face: .

**Comment by neon-mmd** [comment]
@lxrst it has been one month so far, any progress on this issue so far? We would like to know :slightly_smiling_face: .
