### ISSUE TITLE
🐛 Warning and program crashes with a `not present` error 

### ISSUE THREAD

**Issue by Yakumo-Yukari** [neon-mmd/websurfx#531]
### Description

`System windows 11`
`rust version 1.76.0`

When I use the cargo run command, I get the following error

```
warning: call to `.clone()` on a reference in this situation does nothing
  --> src\results\aggregator.rs:94:31
   |
94 |                     user_agent.clone(),
   |                               ^^^^^^^^ help: remove this redundant call
   |
   = note: the type `str` does not implement `Clone`, so calling `clone` on `&str` copies the reference, which does not do anything and can be removed
   = note: `#[warn(noop_method_call)]` on by default

warning: `websurfx` (lib) generated 1 warning (run `cargo fix --lib -p websurfx` to apply 1 suggestion)
    Finished dev [unoptimized + debuginfo] target(s) in 9m 02s
warning: the following packages contain code that will be rejected by a future version of Rust: html5ever v0.23.0
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
     Running `target\debug\websurfx.exe .`
thread 'main' panicked at src\handler\paths.rs:62:51:
called `Result::unwrap()` on an `Err` value: NotPresent
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\websurfx.exe .` (exit code: 101)
[WARN] - (starship::utils): Executing command "C:\\Program Files\\Git\\cmd\\git.exe" timed out.
[WARN] - (starship::utils): You can set command_timeout in your config to a higher value to allow longer-running commands to keep executing.
```

### Do you want to work on this issue?

Yes

**Comment by neon-mmd** [comment]
Thanks :heart: for taking the time to open this issue. We really appreciate it :+1: as it helps improve our project. :slightly_smiling_face: 

Ok, for the first error, we would suggest you to run the following command `cargo fix --allow-dirty` which will fix it. It looks like you're trying to run the app on Windows. We don't support Windows or macOS right now because most people who use our project use `Linux distros`. As these operating systems are not very good at protecting privacy, so it's not a good idea to run a privacy-focused app on a non-privacy-focused operating system. These operating systems can still spy on what you're doing on your computer. That's why we decided to not support these operating systems for now. If we do get a lot of requests from users to support them, then we might consider supporting them, but for now we do not plan to support them. But yes, if you still want to run the project on these operating systems then there are few options like you can run it via `docker`, virtual machine or `wsl2`. 

For a guide on how to deploy the app via `docker` we would suggest following the guide link provided below:    
- https://github.com/neon-mmd/websurfx/blob/rolling/docs/installation.md#docker-deployment

**Comment by Yakumo-Yukari** [comment]
> Thanks ❤️ for taking the time to open this issue. We really appreciate it 👍 as it helps improve our project. 🙂
> 
> Ok, for the first error, we would suggest you to run the following command `cargo fix --allow-dirty` which will fix it. It looks like you're trying to run the app on Windows. We don't support Windows or macOS right now because most people who use our project use `Linux distros`. As these operating systems are not very good at protecting privacy, so it's not a good idea to run a privacy-focused app on a non-privacy-focused operating system. These operating systems can still spy on what you're doing on your computer. That's why we decided to not support these operating systems for now. If we do get a lot of requests from users to support them, then we might consider supporting them, but for now we do not plan to support them. But yes, if you still want to run the project on these operating systems then there are few options like you can run it via `docker`, virtual machine or `wsl2`.
> 
> For a guide on how to deploy the app via `docker` we would suggest following the guide link provided below:
> 
> * https://github.com/neon-mmd/websurfx/blob/rolling/docs/installation.md#docker-deployment

OK  THX
