### ISSUE TITLE
:sparkles:  Rose pine colorscheme variants for the search engine

### ISSUE THREAD

**Issue by phetzy** [neon-mmd/websurfx#546]
### What would you like to share?

 I made 3 color schemes inspired by the original 3 color palettes: Rose Pine, Rose Pine Moon, Rose Pine Dawn. I want to add more customization to users especially since these color schemes are some of the most popular with linux users dot files. So what better than to have their web surfing match their desktop environment. The change to the style.css svg matches the foreground color but does not match with the logo when you reach the index. I made this simple change to add continuity between the appearances in the logos.

### Do you want to work on this issue?

Yes

**Comment by neon-mmd** [comment]
Thanks :heart: for taking the time to open the issue. We really appreciate it :+1: as it helps improve our project. :slightly_smiling_face: 

Since you have requested to work on this issue. So we are assigning the issue to you. You may start working on this issue right away :rocket: :slightly_smiling_face: .
