### ISSUE TITLE
✨ Setup CI to build and publish a docker image for every release

### ISSUE THREAD

**Issue by netroy** [neon-mmd/websurfx#572]
### Description

Right now the last tag that was published to docker hub is `1.0.0`, which is 8 months old.
If the CI is configured to build and publish these docker images, people can more easily use latest versions.

### Do you want to work on this issue?

Yes

**Comment by neon-mmd** [comment]
Sorry for the late reply.

Thanks ❤️ for opening this issue. We really appreciate it 👍 as by opening them it really helps improve the project 🙂 .

Actually, Sorry but we don't plan to provide a rolling release based docker images because the rolling release contains the latest changes and it can contain potentially breaking changes (like engine removal, config option additions or renaming or deletion, etc) which can really effect user experience in a bad way. So we don't want to provide the rolling release based docker images to the user on the project side. But we are open to community contributions in this area. So if you do want to support it from your side then we would really appreciate it 🙁 .

So again sorry but because of the above mentioned issue. We will be closing this issue as not planned. 🙂
